[package]
name = "ubc125"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.4", features = ["derive", "env"] }
crossterm = "0.29.0"
ratatui = "0.30.2"
serialport = { version = "4.9.0", default-features = false }
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
tonic = "0.14.6"
tonic-reflection = "0.14.6"
tonic-web = "0.14.6"
tower-http = { version = "0.7.0", features = ["cors"] }
ubc125-grpc = { version = "0.1.0", path = "./lib/grpc/rust-gen" }
